version: '3.8'
services:
  movies:
    image: roopesh123/paytmmovies
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: roopesh123/paytmtrain
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: roopesh123/paytmdth
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: roopesh123/paytmrecharge
    ports:
      - "84:80"
    deploy:
      replicas: 3
